### ISSUE TITLE
Is it impossible to install HDP-1.3 stack by sequenceiq/ambari:1.7.0 image?

### ISSUE THREAD

**Issue by rain1024** [sequenceiq/docker-ambari#122]
Is it impossible to use `sequenceiq/ambari:1.7.0` to install HDP-1.3 stack?

I try it but it fail

Here are my steps

```
curl -Lo .amb j.mp/docker-ambari-170 && . .amb
amb-start-cluster 3

amb-shell
```

In `amb-shell`

```
blueprint add --url https://gist.github.com/rain1024/991045e49e73393c16f0/raw/42b2e54d12bccfd8a090dbe68dd3dd5586387662/hdp-1.3
cluster build --blueprint hdp-1.3
cluster autoAssign
cluster create
```

But it failed to install HDFS

I went to ambari web in <ambari_web>:8080 and get some error logs

```
2016-03-17 05:52:11,220 - Error while executing command 'install':
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 123, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/1.3.2/services/HDFS/package/scripts/hdfs_client.py", line 29, in install
    self.install_packages(env, params.exclude_packages)
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 188, in install_packages
    Package(name)
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 148, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 149, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 115, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/__init__.py", line 40, in action_install
    self.install_package(package_name)
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/yumrpm.py", line 36, in install_package
    shell.checked_call(cmd)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 36, in checked_call
    return _call(command, logoutput, True, cwd, env, preexec_fn, user, wait_for_finish, timeout, path)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 102, in _call
    raise Fail(err_msg)
Fail: Execution of '/usr/bin/yum -d 0 -e 0 -y install hadoop-native' returned 1. Error: Package: hadoop-native-1.2.0.1.3.7.0-2.el6.x86_64 (HDP-1.3)
           Requires: hadoop = 1.2.0.1.3.7.0-2.el6
           Installed: hadoop-2.6.0.2.2.0.0-2041.el6.noarch (@HDP-2.2)
               hadoop = 2.6.0.2.2.0.0-2041.el6
           Available: hadoop-1.2.0.1.3.7.0-2.el6.x86_64 (HDP-1.3)
               hadoop = 1.2.0.1.3.7.0-2.el6
               hadoop
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by biharitomi** [comment]
Hi @rain1024 ,

Ambari 1.7.0 came with newer HDP as the error shows in the log:
`Installed: hadoop-2.6.0.2.2.0.0-2041.el6.noarch (@HDP-2.2)
               hadoop = 2.6.0.2.2.0.0-2041.el6`
In the [release notes](http://hortonworks.com/products/releases/hdp-1-3/) you can find which Ambari came with the HDP 1.3 as default.
We have a newer version of [Ambari functions] (https://hub.docker.com/r/sequenceiq/ambari/) that depends on Ambari 2.2.1, we recommend you to use the newer version of Ambari functions and HDP too if it is possible.

Br,
Tamas

**Comment by rain1024** [comment]
thank you @biharitomi 

As your recommender, I will you HDP 2.2, which is already supported by docker-ambari
